version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app

# ADD THIS NEW PERMISSIONS SECTION
permissions:
  - object: /home/ec2-user/app/scripts/start_server.sh
    owner: root
    group: root
    mode: 755 # This adds execute permissions
  - object: /home/ec2-user/app/scripts/stop_server.sh
    owner: root
    group: root
    mode: 755 # This adds execute permissions

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root